<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrrGOQB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrrGOQB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWrrGOQB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWrrGOQB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWrrGOQB\App_KernelDevDebugContainer([
    'container.build_hash' => 'WrrGOQB',
    'container.build_id' => 'ff72cd62',
    'container.build_time' => 1583954245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrrGOQB');
