<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6Blaqx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6Blaqx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD6Blaqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD6Blaqx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD6Blaqx\App_KernelDevDebugContainer([
    'container.build_hash' => 'D6Blaqx',
    'container.build_id' => '1e86de17',
    'container.build_time' => 1584032571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6Blaqx');
